FROM python:2.7.13

ENV WEBHOOKS_PATH    /opt/cd-webhooks

WORKDIR ${WEBHOOKS_PATH}/src

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 && \
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.4.list
    
RUN apt-get -y update && apt-get -y install sudo mongodb-org-shell && apt-get clean

ADD server ${WEBHOOKS_PATH}/src/server

CMD python $WEBHOOKS_PATH/src/server/server.py

